services:

  mysql:
    image: mysql:8.0
    container_name: product-api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: zestIndia_db
    ports:
      - "3307:3306"

  product-api:
    build: .
    container_name: product-api-container
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - mysql